### ISSUE TITLE
cwl-tes fork used in WES-ELIXIR lost some important bug fixes

### ISSUE THREAD

**Issue by aniewielska** [elixir-europe/WES-ELIXIR#100]
Current version of WES-ELIXIR (dev branch) still uses forked version of cwl-tes, but the patch applied there lost some important bug fixes (notably the bug that forces users to declare all resource requirements, as declaring only some results in "cwl-tes does not yet support dynamic resource requests" ).
The bug fix is here: https://github.com/ohsu-comp-bio/cwl-tes/commit/62577e53289889505ca30d3aa60e02975ea8c603

For integrated WES-TES it would be optimal, if the current version of cwl-tes was used (https://github.com/ohsu-comp-bio/cwl-tes/commit/4d7e2e572fabd9b67a9f19e94ede969c53ae8c5c) as it contains all bug fixes for cwl-tes.

**Comment by uniqueg** [comment]
The current forked version uniqueg/cwl-tes-temp@e37090e00f2573e84becec30f0ade9c5003820b3 used in both the `dev` and `master` branches now (since commit b8cd3a7949433866258db5db8295cf642b3b0634) includes those patches and was up-to-date with the `cwl-tes` version as of May 22, 2019.

However, I will leave this issue open for now to remind myself to push for the `cwl-tes` maintainers to merge the OAuth-related changes introduced in our fork in favor of maintaining a fork just for that.

**Comment by uniqueg** [comment]
I've just filed another PR with the `cwl-tes` maintainers: ohsu-comp-bio/cwl-tes/pull/29
I will also ask Michael Crusoe personally when I see him later.

**Comment by uniqueg** [comment]
Closed by ohsu-comp-bio/cwl-tes/pull/29 and #124
